version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: mongo_solar_explorer
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: solar_explorer
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
